# Generated by Django 5.2 on 2025-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("distance_km", models.FloatField()),
                ("toll_gates", models.IntegerField()),
                ("fuel_cost", models.FloatField()),
                ("toll_cost", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("journey_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
